name: uni_dating_app
description: Dating app for university

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.8.5

  cupertino_icons: ^1.0.2

  # ui
  animated_gesture_detector: ^1.0.0
  animated_bottom_navigation_bar: ^1.0.1

  # dev
  rxdart: ^0.27.2
  json_annotation: ^4.4.0
  uuid: ^3.0.6
  intl: ^0.17.0

  # database
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_database: ^9.0.8
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.5

flutter:

  uses-material-design: true
  assets:
    - lib/assets/imgs/UploadPhoto.png
    - lib/assets/imgs/AppLogo.png